name: Build and Deploy with MicroK8s

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    name: Build and Push Image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Mostrar rama actual
        run: echo "Rama actual:${{ github.ref }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set OWNER_LC
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${OWNER_LC}/fronend_aventureros:latest ./frontend_Aventureros

      - name: Push Docker image
        run: docker push ghcr.io/${OWNER_LC}/fronend_aventureros:latest

  deploy-onpremise:
    name: Deploy on MicroK8s On-Premise
    runs-on: main
    needs: build-and-publish

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Apply Kubernetes deployment
        run: sudo microk8s kubectl apply -f frontend_Aventureros/k8s/deployment.yaml

      - name: Restart Kubernetes deployment
        run: sudo microk8s kubectl rollout restart deployment/fronend-aventureros -n aventureros
